version: '3.8'

services:
  nextjs:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: nextjs_app
    working_dir: /app
    volumes:
      - .:/app:cached
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    networks:
      - etreereum_network
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: etreereum_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - etreereum_network


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql

    depends_on:
      - mysql

    networks:
      - etreereum_network

networks:
  etreereum_network:

volumes:
  mysql_data: